# typed: strict
# frozen_string_literal: true

# Homebrew formula for the Superopen CLI (`so`).
#
# Generated by ishanjainn/superopen's Release / Packages workflow.
# Manual install: brew install ishanjainn/superopen/so
class So < Formula
  desc "Native code graph and coding-session observability"
  homepage "https://github.com/ishanjainn/superopen"
  version "0.5.2"
  license "Apache-2.0"

  head do
    url "https://github.com/ishanjainn/superopen.git", branch: "main"
    depends_on "go" => :build
  end

  on_macos do
    on_arm do
      url "https://github.com/ishanjainn/superopen/releases/download/cli-0.5.2/so-darwin-arm64.tar.gz"
      sha256 "996b7832deeef6b6e73ba412ba5d54e05907e856b29afe33ad2d838d42ee42b6"
    end
    on_intel do
      url "https://github.com/ishanjainn/superopen/releases/download/cli-0.5.2/so-darwin-amd64.tar.gz"
      sha256 "ff69f0081dfd58f28daeb6e3b59f3b76643b56b767f167d85d1f02996ac80b6b"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/ishanjainn/superopen/releases/download/cli-0.5.2/so-linux-arm64.tar.gz"
      sha256 "b656919030ab7445c6730965c20bd58f77ba456e07f51e87a89793db20eff3dd"
    end
    on_intel do
      url "https://github.com/ishanjainn/superopen/releases/download/cli-0.5.2/so-linux-amd64.tar.gz"
      sha256 "c65ab39e0fbb4fe274336cbef991f88933f6076c51d59091baa594ffb12d2acb"
    end
  end

  resource "web" do
    url "https://github.com/ishanjainn/superopen/releases/download/cli-0.5.2/so-web.tar.gz"
    sha256 "cfbf12995c32ca2cd843079584c8778514effe028d4315b6c6a64b97c86831fd"
  end

  depends_on "node"

  def install
    if build.head?
      system "go", "build", "-o", bin/"so", "./cmd/so"
      cd "web" do
        system "npm", "install", "--ignore-scripts"
        system "npm", "run", "build"
      end
      standalone = buildpath/"web/.next/standalone"
      odie "web UI standalone build missing" unless (standalone/"server.js").exist?
      static_dir = buildpath/"web/.next/static"
      if static_dir.exist?
        (standalone/".next/static").mkpath
        static_dir.children.each { |child| cp_r child, standalone/".next/static"/child.basename }
      end
      public_dir = buildpath/"web/public"
      if public_dir.exist?
        (standalone/"public").mkpath
        public_dir.children.each { |child| cp_r child, standalone/"public"/child.basename }
      end
      dst = share/"superopen/web"
      dst.mkpath
      standalone.children.each { |child| cp_r child, dst/child.basename }
    else
      bin.install Dir["so*"].first => "so"
      resource("web").stage do
        dst = share/"superopen/web"
        dst.mkpath
        Pathname(".").children.each { |child| cp_r child, dst/child.basename }
      end
    end
  end

  def caveats
    <<~EOS
      Run `so install` once to wire coding-agent hooks.
      Then in any repo: `so init` and `so dev`.
      `so dev` needs Node.js (already installed as a dependency).
    EOS
  end

  test do
    assert_match "so", shell_output("#{bin}/so --help")
  end
end
