# typed: strict
# frozen_string_literal: true

# Homebrew formula for the Superopen CLI (`so`).
#
# Generated by ishanjainn/superopen's Release / Packages workflow.
# Manual install: brew install ishanjainn/superopen/so
class So < Formula
  desc "Native code graph and coding-session observability"
  homepage "https://github.com/ishanjainn/superopen"
  version "0.5.1"
  license "Apache-2.0"

  head do
    url "https://github.com/ishanjainn/superopen.git", branch: "main"
    depends_on "go" => :build
  end

  on_macos do
    on_arm do
      url "https://github.com/ishanjainn/superopen/releases/download/cli-0.5.1/so-darwin-arm64.tar.gz"
      sha256 "b6d4c9eff87979b2aeb90b6436bc1e569436d464c465fdbb1f9d3fa25f5534ae"
    end
    on_intel do
      url "https://github.com/ishanjainn/superopen/releases/download/cli-0.5.1/so-darwin-amd64.tar.gz"
      sha256 "e83a2653a8e87a94615ea3f3de15013438518b9ebd0f723648128a06587764a1"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/ishanjainn/superopen/releases/download/cli-0.5.1/so-linux-arm64.tar.gz"
      sha256 "cf67d8f72aa80d4fb348073eb462ab08a1b05e2e38e73fb57a0a4f3eabfaddae"
    end
    on_intel do
      url "https://github.com/ishanjainn/superopen/releases/download/cli-0.5.1/so-linux-amd64.tar.gz"
      sha256 "d81bd1e8a56f555cc034b7aac629fe1f86befd8f1aaf4de8328e4e0b108be67c"
    end
  end

  resource "web" do
    url "https://github.com/ishanjainn/superopen/releases/download/cli-0.5.1/so-web.tar.gz"
    sha256 "6ce7018ff52c6a99dd77f193e702c6b28f1c6a9e95c3bc01790b37dfbbae0431"
  end

  depends_on "node"

  def install
    if build.head?
      system "go", "build", "-o", bin/"so", "./cmd/so"
      cd "web" do
        system "npm", "install", "--ignore-scripts"
        system "npm", "run", "build"
      end
      standalone = buildpath/"web/.next/standalone"
      odie "web UI standalone build missing" unless (standalone/"server.js").exist?
      static_dir = buildpath/"web/.next/static"
      if static_dir.exist?
        (standalone/".next/static").mkpath
        static_dir.children.each { |child| cp_r child, standalone/".next/static"/child.basename }
      end
      public_dir = buildpath/"web/public"
      if public_dir.exist?
        (standalone/"public").mkpath
        public_dir.children.each { |child| cp_r child, standalone/"public"/child.basename }
      end
      dst = share/"superopen/web"
      dst.mkpath
      standalone.children.each { |child| cp_r child, dst/child.basename }
    else
      bin.install Dir["so*"].first => "so"
      resource("web").stage do
        dst = share/"superopen/web"
        dst.mkpath
        Pathname(".").children.each { |child| cp_r child, dst/child.basename }
      end
    end
  end

  def caveats
    <<~EOS
      Run `so install` once to wire coding-agent hooks.
      Then in any repo: `so init` and `so dev`.
      `so dev` needs Node.js (already installed as a dependency).
    EOS
  end

  test do
    assert_match "so", shell_output("#{bin}/so --help")
  end
end
