# typed: strict
# frozen_string_literal: true

# Homebrew formula for the Superopen CLI (`so`).
#
# Generated by ishanjainn/superopen's Release / Packages workflow.
# Manual install: brew install ishanjainn/superopen/so
class So < Formula
  desc "Native code graph and coding-session observability"
  homepage "https://github.com/ishanjainn/superopen"
  version "0.5.0"
  license "Apache-2.0"

  head do
    url "https://github.com/ishanjainn/superopen.git", branch: "main"
    depends_on "go" => :build
  end

  on_macos do
    on_arm do
      url "https://github.com/ishanjainn/superopen/releases/download/cli-#{version}/so-darwin-arm64.tar.gz"
      sha256 "202fa3d6699cb410c56aed1cb4902d17d4206c9d03a9f29e5e65f08675067531"
    end
    on_intel do
      url "https://github.com/ishanjainn/superopen/releases/download/cli-#{version}/so-darwin-amd64.tar.gz"
      sha256 "802acf4c886fb44cd08bf2e76acf9ab978c94d0f4e7a7dd3ad38d496a8522eb9"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/ishanjainn/superopen/releases/download/cli-#{version}/so-linux-arm64.tar.gz"
      sha256 "c804dffbd1cb481b44fcd30f590303607725b4e9299b8cc95fd374745a57520e"
    end
    on_intel do
      url "https://github.com/ishanjainn/superopen/releases/download/cli-#{version}/so-linux-amd64.tar.gz"
      sha256 "f191736da95f50f01e11dce9d56182d1b4f944f8ce21668ecd7845064d761e7d"
    end
  end

  resource "web" do
    url "https://github.com/ishanjainn/superopen/releases/download/cli-#{version}/so-web.tar.gz"
    sha256 "83aa1b99830c1647bc3e558d82c955a6bbe0c6389f0138a2425e4fc708caa576"
  end

  depends_on "node"

  def install
    if build.head?
      system "go", "build", "-o", bin/"so", "./cmd/so"
      cd "web" do
        system "npm", "install", "--ignore-scripts"
        system "npm", "run", "build"
      end
      standalone = buildpath/"web/.next/standalone"
      odie "web UI standalone build missing" unless (standalone/"server.js").exist?
      static_dir = buildpath/"web/.next/static"
      if static_dir.exist?
        (standalone/".next/static").mkpath
        static_dir.children.each { |child| cp_r child, standalone/".next/static"/child.basename }
      end
      public_dir = buildpath/"web/public"
      if public_dir.exist?
        (standalone/"public").mkpath
        public_dir.children.each { |child| cp_r child, standalone/"public"/child.basename }
      end
      dst = share/"superopen/web"
      dst.mkpath
      standalone.children.each { |child| cp_r child, dst/child.basename }
    else
      bin.install Dir["so*"].first => "so"
      resource("web").stage do
        dst = share/"superopen/web"
        dst.mkpath
        Pathname(".").children.each { |child| cp_r child, dst/child.basename }
      end
    end
  end

  def caveats
    <<~EOS
      Run `so install` once to wire coding-agent hooks.
      Then in any repo: `so init` and `so dev`.
      `so dev` needs Node.js (already installed as a dependency).
    EOS
  end

  test do
    assert_match "so", shell_output("#{bin}/so --help")
  end
end
